# Generated by Django 5.2.15 on 2026-07-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Session')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('converted', 'Оформлений'), ('abandoned', 'Покинутий')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'db_table': 'commerce_cart',
                'indexes': [models.Index(condition=models.Q(('status', 'active')), fields=['session_key'], name='commerce_cart_active_sess')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='new', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=32)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_company', models.CharField(blank=True, default='', max_length=255)),
                ('customer_comment', models.TextField(blank=True, default='')),
                ('shipping_method', models.CharField(choices=[('pickup', 'Самовивіз'), ('delivery', 'Delivery'), ('nova_poshta', 'Нова Пошта')], max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('np_city_ref', models.CharField(blank=True, default='', max_length=64)),
                ('np_city_name', models.CharField(blank=True, default='', max_length=255)),
                ('np_warehouse_ref', models.CharField(blank=True, default='', max_length=64)),
                ('np_warehouse_name', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(choices=[('invoice', 'Рахунок-фактура'), ('cash', 'Готівка')], max_length=20)),
                ('subtotal_uah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_uah', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='commerce.cart')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'commerce_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(blank=True, default='', max_length=64)),
                ('product_name', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'db_table': 'commerce_order_item',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cart_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Позиція кошика',
                'verbose_name_plural': 'Позиції кошика',
                'db_table': 'commerce_cart_item',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='commerce_cart_item_unique_product'), models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='commerce_cart_item_qty_gte_1')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='commerce_or_status_50df41_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='commerce_or_custome_26502e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='commerce_or_created_1aac36_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='commerce_order_item_qty_gte_1'),
        ),
    ]
