# Generated by Django 5.2.15 on 2026-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost_uah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('warehouse', 'На вантажне відділення'), ('doors', 'Адресна доставка (двері)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_warehouse_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_warehouse_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
