# Generated by Django 5.2.15 on 2026-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('kind', models.CharField(choices=[('order', 'Замовлення'), ('contact_lead', 'Зворотний звʼязок')], max_length=32)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Надіслано'), ('failed', 'Помилка')], max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Email лог',
                'verbose_name_plural': 'Email логи',
                'db_table': 'notifications_email_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
