services:
  nginx:
    restart: always

  web:
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DEBUG: "False"

  cron:
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production

  db:
    restart: always
    env_file:
      - .env
