# Generated by Django 5.2.15 on 2026-07-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO keywords')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='catalog/categories/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Батьківська')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'catalog_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO keywords')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна UAH')),
                ('availability', models.CharField(choices=[('in_stock', 'В наявності'), ('on_order', 'Під замовлення'), ('out_of_stock', 'Немає в наявності'), ('call', 'Уточнюйте')], default='in_stock', max_length=32, verbose_name='Наявність')),
                ('availability_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Текст статусу')),
                ('sku', models.CharField(blank=True, default='', max_length=64, verbose_name='SKU')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'catalog_product',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('image', models.ImageField(upload_to='catalog/products/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Alt')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'db_table': 'catalog_product_image',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'sort_order'], name='catalog_cat_parent__57266d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'sort_order'], name='catalog_pro_is_publ_afe672_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='catalog_pro_categor_7c1c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['availability'], name='catalog_pro_availab_1dcb5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price_uah__isnull', True), ('price_uah__gte', 0), _connector='OR'), name='catalog_product_price_uah_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('sku',), name='catalog_product_sku_unique_if_set'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='catalog_product_image_one_main'),
        ),
    ]
