# Generated by Django 5.2.15 on 2026-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='card_badge_style',
            field=models.CharField(choices=[('stock', 'Наявність (зелений)'), ('top', 'TOP / акцент (жовтий)'), ('sale', 'Знижка (бежевий)'), ('soft', 'Нейтральний')], default='stock', max_length=16, verbose_name='Стиль бейджа'),
        ),
        migrations.AddField(
            model_name='category',
            name='card_badge_text',
            field=models.CharField(blank=True, default='', help_text='Напр. TOP, Новинка. Порожньо = без бейджа.', max_length=40, verbose_name='Бейдж на картці'),
        ),
        migrations.AddField(
            model_name='product',
            name='card_badge_style',
            field=models.CharField(blank=True, choices=[('stock', 'Наявність (зелений)'), ('top', 'TOP / акцент (жовтий)'), ('sale', 'Знижка (бежевий)'), ('soft', 'Нейтральний')], default='stock', max_length=16, verbose_name='Стиль бейджа'),
        ),
        migrations.AddField(
            model_name='product',
            name='card_badge_text',
            field=models.CharField(blank=True, default='', help_text='Напр. TOP, -10%. Порожньо = текст наявності.', max_length=40, verbose_name='Бейдж на картці'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_label',
            field=models.CharField(blank=True, default='', help_text='Кастомний текст наявності (PDP і бейдж, якщо бейдж картки порожній).', max_length=120, verbose_name='Текст статусу'),
        ),
    ]
