# Generated by Django 5.2.15 on 2026-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_card_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.PositiveIntegerField(default=5, verbose_name='Висота, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.PositiveIntegerField(default=200, verbose_name='Довжина, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=25, max_digits=8, verbose_name='Вага, кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.PositiveIntegerField(default=110, verbose_name='Ширина, см'),
        ),
    ]
