# Generated by Django 5.2.15 on 2026-07-30 08:40

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('icon', models.ImageField(blank=True, upload_to='content/advantages/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'db_table': 'content_home_advantage',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to='content/banners/')),
                ('image_mobile', models.ImageField(blank=True, upload_to='content/banners/mobile/')),
                ('link_url', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Банер головної',
                'verbose_name_plural': 'Банери головної',
                'db_table': 'content_home_banner',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('site_name', models.CharField(default='Soliron', max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='content/logo/')),
                ('phone_primary', models.CharField(blank=True, default='', max_length=32)),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('map_embed_url', models.URLField(blank=True, default='')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notify_email', models.EmailField(blank=True, default='', max_length=254)),
                ('gtm_container_id', models.CharField(blank=True, default='', max_length=32)),
                ('ga4_measurement_id', models.CharField(blank=True, default='', max_length=32)),
                ('robots_txt', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
                'db_table': 'content_site_settings',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, default='', verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO keywords')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('body', tinymce.models.HTMLField()),
                ('cover_image', models.ImageField(blank=True, upload_to='content/blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'db_table': 'content_blog_post',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='content_blo_is_publ_e59aa1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('message', models.TextField()),
                ('source_url', models.CharField(blank=True, default='', max_length=512)),
                ('is_processed', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заявка ЗЗ',
                'verbose_name_plural': 'Заявки ЗЗ',
                'db_table': 'content_contact_lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_processed', '-created_at'], name='content_con_is_proc_e7153a_idx')],
            },
        ),
    ]
