# Generated by Django 5.2.15 on 2026-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='content/banners/'),
        ),
    ]
