# Generated by Django 5.2.15 on 2026-07-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_home_banner_image_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(blank=True, help_text='Desktop hero: рекомендуємо 1400×1050 px (співвідношення 4:3, JPG/WebP). Щоб видалити поточне зображення — позначте «Очистити» і збережіть.', upload_to='content/banners/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Mobile hero: рекомендуємо 800×1000 px (співвідношення 4:5, JPG/WebP). Щоб видалити — позначте «Очистити» і збережіть.', upload_to='content/banners/mobile/'),
        ),
    ]
