# Generated by Django 5.2.15 on 2026-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_home_banner_image_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Листи про замовлення та зворотний звʼязок', max_length=254, verbose_name='Email адміністратора'),
        ),
    ]
