# Generated by Django 5.2.15 on 2026-08-03 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_site_settings_notify_email_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обкладинка картки та шапки статті. Дозволені формати: jpg, jpeg, png, webp. Якщо фото більше за 1200×900 px — автоматично обрізається по центру до 4:3. Щоб видалити — «Очистити / видалити зображення» → Зберегти.', upload_to='content/blog/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
