# Generated by Django 5.2.15 on 2026-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_blog_cover_image_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status_text', models.CharField(blank=True, default='Працюємо з 2012 року • 500+ встановлених обʼєктів', max_length=255, verbose_name='Статус-рядок')),
                ('title_before', models.CharField(blank=True, default='Енергія', max_length=120, verbose_name='Заголовок (перед акцентом)')),
                ('title_highlight', models.CharField(blank=True, default='сонця', max_length=80, verbose_name='Заголовок (акцент)')),
                ('title_after', models.CharField(blank=True, default='для вашого дому та бізнесу', max_length=160, verbose_name='Заголовок (після акценту)')),
                ('lead', models.TextField(blank=True, default='Проєктування, постачання та монтаж сонячних електростанцій під ключ. Автономність, прозорі терміни та гарантія до 30 років.', verbose_name='Підзаголовок')),
                ('cta_primary_label', models.CharField(blank=True, default='Каталог обладнання', max_length=80, verbose_name='CTA основна — текст')),
                ('cta_primary_url', models.CharField(blank=True, default='/katalog/', max_length=512, verbose_name='CTA основна — URL')),
                ('cta_secondary_label', models.CharField(blank=True, default='Безкоштовна консультація', max_length=80, verbose_name='CTA друга — текст')),
                ('cta_secondary_url', models.CharField(blank=True, default='/kontakty/', max_length=512, verbose_name='CTA друга — URL')),
                ('image', models.ImageField(blank=True, help_text='Desktop hero: 1400×1050 px (4:3, JPG/WebP). Очистити — галочка «Очистити» і зберегти.', upload_to='content/home/', verbose_name='Hero desktop')),
                ('image_mobile', models.ImageField(blank=True, help_text='Mobile hero: 800×1000 px (4:5, JPG/WebP). Очистити — галочка «Очистити» і зберегти.', upload_to='content/home/mobile/', verbose_name='Hero mobile')),
                ('image_alt', models.CharField(blank=True, default='Soliron — сонячні електростанції', max_length=255, verbose_name='Alt зображення')),
                ('float_badge_title', models.CharField(blank=True, default='Гарантія 30 років', max_length=80, verbose_name='Бейдж — заголовок')),
                ('float_badge_subtitle', models.CharField(blank=True, default='Якість без компромісів', max_length=120, verbose_name='Бейдж — підпис')),
                ('offer_enabled', models.BooleanField(default=True, verbose_name='Показувати пропозицію')),
                ('offer_title', models.CharField(blank=True, default='Каталог сонячних панелей і кріплень', max_length=255, verbose_name='Пропозиція — заголовок')),
                ('offer_subtitle', models.TextField(blank=True, default='', verbose_name='Пропозиція — текст')),
                ('offer_link_label', models.CharField(blank=True, default='Детальніше', max_length=80, verbose_name='Пропозиція — кнопка')),
                ('offer_link_url', models.CharField(blank=True, default='/katalog/', max_length=512, verbose_name='Пропозиція — URL')),
                ('categories_eyebrow', models.CharField(blank=True, default='АСОРТИМЕНТ', max_length=80, verbose_name='Каталог — надзаголовок')),
                ('categories_title', models.CharField(blank=True, default='Каталог обладнання', max_length=160, verbose_name='Каталог — заголовок')),
                ('categories_description', models.CharField(blank=True, default='Оберіть категорію, щоб перейти до товарів.', max_length=255, verbose_name='Каталог — опис')),
                ('advantages_eyebrow', models.CharField(blank=True, default='Чому Soliron', max_length=80, verbose_name='Про нас — надзаголовок')),
                ('advantages_title', models.CharField(blank=True, default='Про нас', max_length=160, verbose_name='Про нас — заголовок')),
                ('advantages_description', models.CharField(blank=True, default='Якість, терміни та підтримка на кожному етапі.', max_length=255, verbose_name='Про нас — опис')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головна сторінка',
                'db_table': 'content_home_page',
            },
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Банер головної (legacy)', 'verbose_name_plural': 'Банери головної (legacy)'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.TextField(blank=True, default='Сонячні панелі та системи кріплень. Корпоративний каталог з оформленням замовлення.', verbose_name='Слоган у футері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram_url',
            field=models.URLField(blank=True, default='', verbose_name='Telegram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати YouTube'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип у шапці. Рекомендовано PNG або SVG з прозорим фоном, висота 40–56 px, ширина до 220 px (напр. 200×48). Якщо порожньо — показується назва сайту з іконкою.', upload_to='content/logo/'),
        ),
    ]
