# Generated by Django 5.2.15 on 2026-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_seed_default_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_eyebrow',
            field=models.CharField(blank=True, default='Звʼязок', max_length=80, verbose_name='Контакти — надзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_form_title',
            field=models.CharField(blank=True, default='Зворотний звʼязок', max_length=120, verbose_name='Заголовок форми'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_info_title',
            field=models.CharField(blank=True, default='Реквізити', max_length=120, verbose_name='Заголовок блоку реквізитів'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_lead',
            field=models.TextField(blank=True, default='Напишіть нам або зателефонуйте — відповімо з робочими деталями.', verbose_name='Контакти — підзаголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_map_title',
            field=models.CharField(blank=True, default='Як нас знайти', max_length=120, verbose_name='Заголовок карти'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contacts_title',
            field=models.CharField(blank=True, default='Контакти', max_length=160, verbose_name='Контакти — заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва / ФОП'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_edrpou',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='ЄДРПОУ / ІПН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_iban',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_telegram_url',
            field=models.CharField(blank=True, default='', help_text='Напр. https://t.me/username', max_length=255, verbose_name='Telegram (посилання)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_viber_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати Viber'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_viber_url',
            field=models.CharField(blank=True, default='', help_text='Напр. viber://chat?number=%2B380XXXXXXXXX', max_length=255, verbose_name='Viber (посилання)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='Показати WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_whatsapp_url',
            field=models.CharField(blank=True, default='', help_text='Напр. https://wa.me/380XXXXXXXXX', max_length=255, verbose_name='WhatsApp (посилання)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_schedule',
            field=models.TextField(blank=True, default='Пн–Пт: 09:00–18:00\nСб–Нд: вихідний', help_text='Кожен рядок — окремий пункт графіка.', verbose_name='Графік роботи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Звичайний текст, можна кілька рядків. Без HTML-редактора.', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Google Maps → Поділитися → Вставити карту → скопіюйте весь код <iframe …> або лише значення src=…. Система збереже URL для відображення.', verbose_name='Карта Google Maps'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Додатковий телефон'),
        ),
    ]
