# Generated by Django 5.2.15 on 2026-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_contacts_page_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', help_text='Клікніть у велике поле нижче і вставте (Cmd+V) код з Google Maps. Підходить весь блок <iframe …></iframe> або лише посилання з src=…. Після збереження карта зʼявиться на сторінці «Контакти».', verbose_name='Вставте сюди код карти'),
        ),
    ]
