# Generated by Django 5.2.15 on 2026-08-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_map_embed_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Логотип у шапці (PNG з прозорим фоном). Рекомендований розмір файлу: 424×100 px (@2x для висоти ~48 px у десктоп-шапці; на мобільному CSS показує ~40 px). Ширина в шапці до ~220 px. Оригінал: static/images/logo-soliron.png. Щоб повернути оригінал після заміни — очистіть поле (галочка «Повернути оригінальний логотип») і збережіть.', upload_to='content/logo/'),
        ),
    ]
