# Generated by Django 5.2 — ContentPage + seed Ads legal placeholders

from django.db import migrations, models
import tinymce.models


PLACEHOLDER_NOTE = (
    "<p><strong>Чернетка для юриста.</strong> "
    "Замініть цей текст у адмінці (Інфо-сторінки) на фінальну редакцію.</p>"
)

SEED_PAGES = (
    {
        "slug": "oplata-i-dostavka",
        "title": "Оплата і доставка",
        "sort_order": 10,
        "seo_title": "Оплата і доставка",
        "seo_description": "Умови оплати та доставки замовлень Soliron.",
        "body": (
            f"{PLACEHOLDER_NOTE}"
            "<h2>Оплата</h2>"
            "<p>Онлайн-оплата на сайті відсутня. Доступні способи: "
            "рахунок-фактура або готівка — за домовленістю з менеджером.</p>"
            "<h2>Доставка</h2>"
            "<p>Самовивіз, курʼєр Delivery Auto (відділення або двері), "
            "відділення Нової Пошти. Вартість доставки узгоджується окремо.</p>"
        ),
    },
    {
        "slug": "povernennya-ta-obmin",
        "title": "Повернення та обмін",
        "sort_order": 20,
        "seo_title": "Повернення та обмін",
        "seo_description": "Умови повернення та обміну товарів Soliron.",
        "body": (
            f"{PLACEHOLDER_NOTE}"
            "<p>Опишіть строки, підстави повернення/обміну, стан товару, "
            "порядок звернення та реквізити для повернення коштів "
            "відповідно до Закону України «Про захист прав споживачів».</p>"
        ),
    },
    {
        "slug": "publichnyy-dohovir",
        "title": "Публічний договір",
        "sort_order": 30,
        "seo_title": "Публічний договір (оферта)",
        "seo_description": "Публічний договір купівлі-продажу Soliron.",
        "body": (
            f"{PLACEHOLDER_NOTE}"
            "<p>Текст публічної оферти / договору купівлі-продажу: "
            "сторони, предмет, ціна, порядок оплати й доставки, "
            "відповідальність, форс-мажор, реквізити продавця.</p>"
        ),
    },
    {
        "slug": "polityka-konfidentsiynosti",
        "title": "Політика конфіденційності",
        "sort_order": 40,
        "seo_title": "Політика конфіденційності",
        "seo_description": "Політика обробки персональних даних Soliron.",
        "body": (
            f"{PLACEHOLDER_NOTE}"
            "<p>Опишіть, які персональні дані збираються (замовлення, ЗЗ), "
            "мету обробки, строк зберігання, права субʼєкта даних та "
            "контакти відповідальної особи згідно із Законом України "
            "«Про захист персональних даних».</p>"
        ),
    },
)


def seed_pages(apps, schema_editor):
    ContentPage = apps.get_model("content", "ContentPage")
    for row in SEED_PAGES:
        ContentPage.objects.update_or_create(
            slug=row["slug"],
            defaults={
                "title": row["title"],
                "body": row["body"],
                "is_published": True,
                "sort_order": row["sort_order"],
                "seo_title": row["seo_title"],
                "seo_description": row["seo_description"],
                "seo_keywords": "",
            },
        )


def unseed_pages(apps, schema_editor):
    ContentPage = apps.get_model("content", "ContentPage")
    ContentPage.objects.filter(slug__in=[p["slug"] for p in SEED_PAGES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_contactlead_telegram_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Створено")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Оновлено")),
                ("seo_title", models.CharField(blank=True, default="", max_length=512, verbose_name="SEO title")),
                (
                    "seo_description",
                    models.TextField(blank=True, default="", verbose_name="SEO description"),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="SEO keywords",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="Slug")),
                ("body", tinymce.models.HTMLField(verbose_name="Текст")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубліковано")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Інфо-сторінка",
                "verbose_name_plural": "Інфо-сторінки",
                "db_table": "content_page",
                "ordering": ["sort_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "sort_order"],
                        name="content_pag_is_publ_6b0f0a_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_pages, unseed_pages),
    ]
