# Generated by Django 5.2.15 on 2026-07-30 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'НП місто',
                'verbose_name_plural': 'НП міста',
                'db_table': 'shipping_np_city',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NPWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('number', models.CharField(blank=True, default='', max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shipping.npcity')),
            ],
            options={
                'verbose_name': 'НП відділення',
                'verbose_name_plural': 'НП відділення',
                'db_table': 'shipping_np_warehouse',
                'indexes': [models.Index(fields=['city', 'is_active'], name='shipping_np_city_id_e57585_idx')],
            },
        ),
    ]
