# Generated by Django 5.2.15 on 2026-08-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('city_id', models.CharField(max_length=64, unique=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255)),
                ('region_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery місто',
                'verbose_name_plural': 'Delivery міста',
                'db_table': 'shipping_delivery_city',
                'ordering': ['name_uk'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('warehouse_id', models.CharField(max_length=64, unique=True)),
                ('name_uk', models.CharField(max_length=255)),
                ('address_uk', models.CharField(blank=True, default='', max_length=512)),
                ('phone', models.CharField(blank=True, default='', max_length=128)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warehouse_type', models.IntegerField(blank=True, null=True)),
                ('is_freight', models.BooleanField(default=True, help_text='Вантажне відділення (не мікро/pickup-only).')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='shipping.deliverycity')),
            ],
            options={
                'verbose_name': 'Delivery склад',
                'verbose_name_plural': 'Delivery склади',
                'db_table': 'shipping_delivery_warehouse',
                'indexes': [models.Index(fields=['city', 'is_active', 'is_freight'], name='shipping_de_city_id_c9a28f_idx')],
            },
        ),
    ]
